### ISSUE TITLE
WordPress: Uncaught TypeError: can't access property "noop", $ is undefined

### ISSUE THREAD

**Issue by herbie4** [oguzhanoya/jquery-steps#19]
Hi, 
I am trying to get this working inside WordPress but keep getting this error: 

`Uncaught TypeError: can't access property "noop", $ is undefined` and also 

`Uncaught TypeError: $(...).steps is not a function`

The dist/jquery-steps.js is loading as depending on jQuery but still get this error. WordPress is running jQuery 3.5.1.
I already tried setting up de init script as below, but still getting the error. Do you have any advice?

`<script>
jQuery( document ).ready(function($) {
  $('#demo').steps({
    onFinish: function () { alert('complete'); }
  });
});
</script>`

**Comment by herbie4** [comment]
UPDATE: I tried switching to jQuery version 1.12.4 and then it is working. Do you have a solution to make it work with the latest jQuery version?

**Comment by oguzhanoya** [comment]
Hi,

The plugin works fine with jQuery 3.5.1 and the latest version. you can look at the [examples](https://github.com/oguzhanoya/jquery-steps/tree/master/examples)

**Comment by vemman** [comment]
> Hi,
> 
> The plugin works fine with jQuery 3.5.1 and the latest version. you can look at the [examples](https://github.com/oguzhanoya/jquery-steps/tree/master/examples)

Sorry for bumping this one. Its same issue I got. And both issue and answer are right.

But the same issue as said it the title still exists. if we use the **jQuery version that's embedded with WordPress**.
I have a feeling its because **$** variable is not available in the jQuery that's with WP.
